### PR TITLE
Added dependencies

### PR DESCRIPTION
**Pull request by Nafees10**
addressing Issue #215

### CODE REVIEW

**Comment by BBasile** [comment]
Is this guaranteed to be the right names on each debian based distribution ?

**Comment by BBasile** [comment]
I think this will be okay after all since Lazarus itself proposes only 1 deb installer

**Comment by Nafees10** [comment]
> Is this guaranteed to be the right names on each debian based distribution ?
these should be same for debian based distors, because most of the package names match the ones listed here http://wiki.freepascal.org/Deploying_Your_Application

**Comment by BBasile** [comment]
Yeah, thanks. Maybe i'll do the RPM myself since i'm on a RPM-based distro.

**Pull request merged**
